apiVersion: "example.com/v1"
kind: CustomCrd
metadata:
  name: test-custom-cr
  {{- if .Values.clusterLabels }}
  labels: {{- toYaml .Values.clusterLabels | nindent 4}}
  {{- end }}
  {{- if .Values.clusterAnnotations }}
  annotations: {{- toYaml .Values.clusterAnnotations | nindent 4}}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  value: "Hello from my custom resource ({{ .Release.Namespace }}, {{ include "cluster.name" . }})! "