apiVersion: v1
kind: Pod
metadata:
  name: debug-sleep
  {{- if .Values.clusterLabels }}
  labels: {{- toYaml .Values.clusterLabels | nindent 4}}
  {{- end }}
  {{- if .Values.clusterAnnotations }}
  annotations: {{- toYaml .Values.clusterAnnotations | nindent 4}}
  {{- end }}
spec:
  containers:
    - name: test
      image: alpine
      command: ["/bin/sh", "-c", "sleep 360000"]
      securityContext:
        runAsUser: 0
        privileged: false
        capabilities:
          add: ["SYS_RESOURCE", "SYS_TIME", "NET_ADMIN"]
  restartPolicy: Never