---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    k0rdent.mirantis.com/managed: "true"
  name: kozmod-oot-repo
  namespace: kcm-system
spec:
  interval: 10m0s
  provider: generic
  type: oci
  url: oci://ghcr.io/kozmod/helm-charts
status: {}

---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: kubevirt-custom-crd-0-2-0
  namespace: kcm-system
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: kubevirt-custom-crd
      version: 0.2.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kozmod-oot-repo